name: Download and modify file from url

on:
  schedule:
    - cron: "0 */3 * * *"
  push:
    branches:
      - main

jobs:
  download_file_and_modify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Download file from url
      run: |
        curl -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt
        
        curl -o cfip4.txt https://www.cloudflare.com/ips-v4
        curl -o cfip6.txt https://www.cloudflare.com/ips-v6

    - name: Modify the file using sed command
      run: |
        echo "#" | sed "s/$/ $(date)/" > chinacidr.list
        sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' chnroutes.txt >> chinacidr.list
        
        echo "#" | sed "s/$/ $(date)/" > cloudflare.list
        sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' cfip4.txt >> cloudflare.list
        echo >> cloudflare.list
        sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' cfip6.txt >> cloudflare.list

    - name: Store the modified file
      run: |
        mkdir -p lists
        mv -f chinacidr.list lists/
        mv -f cloudflare.list lists/
        rm -rf chnroutes.txt cfip4.txt cfip6.txt
      shell: bash

    - name: Commit the changes
      run: |
        git config --global user.name ${{ secrets.USERNAME }}
        git config --global user.email ${{ secrets.EMAIL }}
        git add .
        git commit -m "Auto Update IPLists"
        git push
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
