name: Download and modify file from url

on:
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main

jobs:
  download_file_and_modify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Download file from url
      run: |
        curl --fail -o chnroutes.txt https://raw.githubusercontent.com/misakaio/chnroutes2/master/chnroutes.txt || rm -f chnroutes.txt
        
        curl --fail -o cfip4.txt https://www.cloudflare.com/ips-v4 || rm -f cfip4.txt
        curl --fail -o cfip6.txt https://www.cloudflare.com/ips-v6 || rm -f cfip6.txt

        curl --fail -o lan-ip.txt https://raw.githubusercontent.com/SukkaW/Surge/master/Source/ip/lan.conf || rm -f lan-ip.txt
        curl --fail -o lan-non_ip.txt https://raw.githubusercontent.com/SukkaW/Surge/master/Source/non_ip/lan.conf || rm -f lan-non_ip.txt

        wget --no-verbose https://raw.githubusercontent.com/cokebar/gfwlist2dnsmasq/master/gfwlist2dnsmasq.sh || rm -f gfwlist2dnsmasq.sh
        wget --no-verbose https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt || rm -f gfwlist.txt

    - name: Modify the file using sed command
      run: |
        # ChinaCIDR
        if [ -f chnroutes.txt ]; then
          echo "#" | sed "s/$/ $(date)/" > chinacidr.list
          sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' chnroutes.txt >> chinacidr.list
        fi

        # CloudflareCIDR
        if [ -f cfip4.txt ] || [ -f cfip6.txt ]; then
          echo "#" | sed "s/$/ $(date)/" > cloudflare.list
          [ -f cfip4.txt ] && sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' cfip4.txt >> cloudflare.list
          echo >> cloudflare.list
          [ -f cfip6.txt ] && sed -e '/^#/b' -e 's/^/IP-CIDR,/' -e 's/$/,no-resolve/' cfip6.txt >> cloudflare.list
        fi

        # LAN
        if [ -f lan-ip.txt ] || [ -f lan-non_ip.txt ]; then
          echo "#" | sed "s/$/ $(date)/" > lan.list
          [ -f lan-ip.txt ] && sed -E '/(IP-CIDR|IP-CIDR6),/ s/$/,no-resolve/' lan-ip.txt >> lan.list
          echo >> lan.list
          [ -f lan-non_ip.txt ] && cat lan-non_ip.txt >> lan.list
        fi

        # GFWlist
        if [ -f gfwlist2dnsmasq.sh ] && [ -f gfwlist.txt ]; then
          echo "#" | sed "s/$/ $(date)/" > gfw.list
          bash gfwlist2dnsmasq.sh -o gfwlist.txt
          sed -i 's/server=\//DOMAIN-SUFFIX,/g; s/\/127\.0\.0\.1#5353//g' gfwlist.txt
          cat gfwlist.txt >> gfw.list
        fi

        # ChinaDomain
        echo "#" | sed "s/$/ $(date)/" > chinadomain.list
        curl --fail -s https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list | sed '/# MyList/,/#/ {/# MyList/d; /#/!d}; /# CN域名直连/,/#/ {/# CN域名直连/d; /#/!d}; /# China DNS/,/#/ {/# China DNS/d; /#/!d}' >> chinadomain.list || rm -f chinadomain.list
        
    - name: Store the modified file
      run: |
        mkdir -p lists
        mv -f chinacidr.list lists/ || true
        mv -f cloudflare.list lists/ || true
        mv -f lan.list lists/ || true
        mv -f gfw.list lists/ || true
        mv -f chinadomain.list lists/ || true
        rm -rf chnroutes.txt cfip4.txt cfip6.txt lan-ip.txt lan-non_ip.txt gfwlist2dnsmasq.sh gfwlist.txt
      shell: bash

    - name: Commit the changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Auto Update"
        git push
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
